# Generated by Django 4.0.5 on 2022-06-05 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_smartphone_sd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='for_anonymous_user',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='in_order',
        ),
    ]
